version: "3.9"

services:
  postgres:
    profiles:
      - prod
      - dev
      - test
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./peppermint/db:/data/db
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  client-prod:
    profiles:
      - prod
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 5001:5001
    restart: on-failure
    depends_on:
      - postgres
    environment:
      PORT: 5001
      DB_USERNAME: peppermint
      DB_PASSWORD: 1234
      DB_HOST: postgres
      BASE_URL: http://localhost:5001

  client-dev:
    profiles:
      - dev
      - test
    container_name: peppermint_dev
    image: node:16-alpine
    working_dir: /src/app
    volumes:
      - .:/src/app
    ports:
      - 5001:5001
    restart: on-failure
    depends_on:
      - postgres
    command: yarn run:dev

    environment:
      PORT: 5001
      DB_USERNAME: peppermint
      DB_PASSWORD: 1234
      DB_HOST: postgres
      BASE_URL: http://localhost:5001
